// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://booohlpwrvqtgvlngzrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvb29obHB3cnZxdGd2bG5nenJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjYyODgsImV4cCI6MjA3MDY0MjI4OH0.5O9hsbSxPoPK-GHKT-IqwubPCP_QmTvwZWVvHAkJ2JE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});